### Get All Guides
GET http://localhost:7777/guides
Accept: application/json

### Get Guide by ID
GET http://localhost:7777/guides/1
Accept: application/json

### Create a New Guide
POST http://localhost:7777/guides
Content-Type: application/json

{
  "name": "Jørgen",
  "specialty": "Mountain Climbing",
  "experience": 5
}

### Update a Guide
PUT http://localhost:7777/guides/1
Content-Type: application/json

{
  "name": "Jørgen Updated",
  "specialty": "Mountain and Snow Climbing",
  "experience": 6
}

### Delete a Guide
DELETE http://localhost:7777/guides/1
Accept: application/json
